#!/bin/sh
# Copyright (C) 2018 Sebastien Decourriere

do_luks_open() {
	sh 
	echo Trying to open luks device
	/usr/bin/passphrase-from-tpm | cryptsetup -d - luksOpen /dev/sda2 data
}

boot_hook_add preinit_main do_luks_open

